/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.awt.*;
import java.io.*;


public class App {

    public static void main(String[] args) throws IOException {

        Bitmap im = new Bitmap("test.bmp");
        Bitmap im2 = new Bitmap("test.bmp");
        Bitmap im3 = new Bitmap("test.bmp");

        im.convertToBlackAndWhite();
        im.writeImage("test1.bmp");
        im2.mirror();
        im2.writeImage("test2.bmp");
        im3.convertBlue();
        im3.writeImage("test3.bmp");


        


    }
}


