/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.awt.*;
import java.io.*;


public class App {

    public static void main(String[] args){

        Bitmap im = new Bitmap("test.bmp");
        Bitmap im2 = new Bitmap("test.bmp");
        Bitmap im3 = new Bitmap("test.bmp");

        im.convertToBlackAndWhite();
        im.writeImage("test1.bmp");
        im2.mirror();
        im2.writeImage("test2.bmp");
        im3.convertBlue();
        im3.writeImage("test3.bmp");



// for running from the command line
        // you should enter 3 args ..
        //example:  gradle run --args 'test.bmp run2.bmp black'
        try {

            String inputFile = args[0];
            String outPutFile = args[1];
            String transform = args[2];

            Bitmap input = new Bitmap(inputFile);
            switch (transform) {
                case "mirror":
                    input.mirror();
                    break;
                case "black":
                    input.convertToBlackAndWhite();
                    break;
                case "blue":
                    input.convertBlue();
                    break;

                default:
                    System.out.println("there is no transformation called" + transform + " please choose mirror or black or blue ...");
            }

            input.writeImage(outPutFile);
        }catch(Exception ex){
            System.out.println("an error occurred with the path from the command line ...");

        }



    }
}


